name: Run on Approved PR Merge to Main

on:
  push:
    branches:
      - main

jobs:
  check-pr-label:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR that triggered the push
        id: get_pr
        uses: actions/github-script@v7
        with:
          script: |
            const commits = await github.rest.repos.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha
            });

            const commitSha = commits.data[0].sha;

            const prs = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: commitSha
            });

            if (prs.data.length === 0) {
              core.setFailed("No pull request found for this commit.");
            } else {
              const pr = prs.data[0];
              core.setOutput("pr_number", pr.number);
            }

      - name: Get PR labels
        id: check_label
        uses: actions/github-script@v7
        with:
          script: |
            const pr_number = core.getInput("pr_number") || '${{ steps.get_pr.outputs.pr_number }}';
            const labels = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number
            });

            const approved = labels.data.some(label => label.name === "approved");
            core.setOutput("approved", approved);

      - name: Run job only if approved
        if: steps.check_label.outputs.approved == 'true'
        run: echo "This PR was approved and merged into main!"
