name: Run on Approved PR Merge to Main

on:
  push:
    branches:
      - main
      - test

jobs:
  check-pr-label:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR that triggered the push
        id: get_pr
        uses: actions/github-script@v7
        with:
          script: |
            const commits = await github.rest.repos.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha
            });

            const commitSha = commits.data[0].sha;

            const prs = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: commitSha
            });

            if (prs.data.length === 0) {
              core.setFailed("No pull request found for this commit.");
            } else {
              const pr = prs.data.at(-1);
              console.log(pr);
              console.log(prs);
              core.setOutput("pr_number", pr.number);
            }

      - name: Get PR labels
        id: check_label
        uses: actions/github-script@v7
        with:
          script: |
            const pr_number = core.getInput("pr_number") || '${{ steps.get_pr.outputs.pr_number }}';
            const labels = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number
            });

            const approved = labels.data.some(label => label.name === "table-approve");
            console.log("table-approve", approved)
            core.setOutput("table-approve", approved);

      - name: Check if PR has table-approve label
        if: steps.check_label.outputs.table-approve != 'true'
        run: |
            echo "PR does not have the table-approve label. Nothing to do."

      - name: Get changed files in PR
        if: steps.check_label.outputs.table-approve == 'true'
        id: changed_files
        uses: actions/github-script@v7
        with:
          script: |
            const pr_number = core.getInput("pr_number") || '${{ steps.get_pr.outputs.pr_number }}';
            const files = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number
            });

            const fileNames = files.data
              .filter(file => file.status !== 'removed')
              .map(f => f.filename)
              .join(', ');

            console.log("Changed files:", fileNames);
            core.setOutput("files", fileNames);

      - name: Get files changed
        if: steps.check_label.outputs.table-approve == 'true'
        run: echo ${{ steps.changed_files.outputs.files }}
